[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  [[redirects]]
  from = "/api/*"
  to = "https://zanefit-express-production.up.railway.app/api/:splat"
  status = 200
  force = true
